routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// interface BarInterface {}
// class Bar implements BarInterface {}
// class SecondBar implements BarInterface {}
// App::bind('BarInterface', 'Bar');
// Route::get('bar', function (BarInterface $bar) {
//     dd($bar);
// });


Route::resource('articles', '\App\Http\Controllers\ArticleController');
Route::get('tags/{tag}','\App\Http\Controllers\ArticleController@tags');
Route::match(['get','post'],'/', '\App\Http\Controllers\ArticleController@latest')->name('welcome');
Route::middleware(['auth:sanctum', 'verified'])->get('/manager', function () {
    return 'This page only for managers';
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{   
    use HasFactory;
    
    protected $fillable = [
        'title',
        'body',
        'user_id'
    ];

    public function user() 
    {
        return $this->belongsTo('App\Models\User');
    } // An article is owned by user (belongsTo)

    public function tags() 
    {
        return $this->belongsToMany('App\Models\Tag')->withTimestamps();
    } 

}

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class Tag extends Model
{
    use HasFactory;

    protected $fillable = [
        'name'
    ];

    // public function articles()
    // {
    //     return $this->belongsToMany('App\Model\Article')->withTimestamps();
    // }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
    public function articles()
    {
        return $this->hasMany('App\Article');
    }
    public function isATeamManager()
    {
        return true;
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Tag;
use App\Models\Article;
use App\Models\User;
use GuzzleHttp\Psr7\Header;
use App\Http\Requests\ArticleRequest;

class ArticleController extends Controller
{
    public function __construct(Article $article, Tag $tag) 
    {   
        $this->middleware('auth', ['only'=>['create','edit','destroy']]);
        $this->ArticleModel=$article;
        $this->TagModel=$tag;
    }
    public function index()
    {   
        $article = Article::latest('created_at')->get();
        $user = User::get();
        return view('articles.index', compact('article','user'));
    }
    public function create()
    {   
        $tag = Tag::pluck('name','id');
        return view('articles.create', compact('tag'));
    }
    public function store(ArticleRequest $request)
    {   
        $this->createArticle($request);
        return redirect('articles')->with('status', 'Статья ' .$_POST['title']. ' успешно создана.');
    }
    public function show(Article $article)
    {   
        $user = User::get();
        return view('articles.show', compact('article','user'));
    }
    public function edit($id)
    {   
        $article = Article::query();
        if (auth()->user()->id != 2) {
            $article->where('user_id', auth()->user()->id);
        }
        $article = Article::findOrFail($id);
        $tag = $this->TagModel->pluck('name','id');
        return view('articles.edit', compact('article','tag'));
    }
    public function update(Article $article, ArticleRequest $request)
    {    
        $article->update($request->all());
        $this->syncTags($article, $request->input('tag_list'));
        return redirect('articles')->with('status', 'Статья ' .$article->title. ' успешно изменена.');
    }
    private function syncTags (Article $article, array $tag) 
    {
        $article->tags()->sync($tag);
    }
    public function destroy($id)
    {   
        $article = Article::findOrFail($id);
        $article->delete($id);
        return redirect('articles')->with('status', 'Статья ' .$article->title. ' успешно удалена.');
    }
    public function createArticle (ArticleRequest $request)
    {   
        $requestAll = $request->all();
        $requestAll['user_id'] = auth()->user()->id;
        $article = Article::create($requestAll);
        $this->syncTags($article, $request->input('tag_list'));
        return $article;
    }
    public function latest() 
    {
        $latest = Article::latest()->first(); // объект в ед. числе
        $tag = Tag::pluck('name','id');
        $user = User::get();
        return view('welcome', compact('latest','tag','user'));
    }
    public function tags() 
    {
        $article = Article::latest('created_at')->get(); //коллекции в множ. числе.
        $tag = Tag::pluck('name','id');
        $user = User::get();
        return view('articles.tags', compact('article','user','tag'));
    }

}
    

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Tag;

class TagsController extends Controller
{

    public function show($tag)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/articles/create.blade.php
<x-app-layout>

  <div class="p-3">
    
    <div class="input-group justify-content-center">
      <h3>Добавить новую статью:</h3>
    </div>
    <form action="/articles" method="POST">
      @csrf
      @method('POST')
        @include('articles.form',['titleValue'=>null,'textarea'=>null,'submitButton'=>'Добавить'])
    </form>
    @include('errors.list')
    <div class="input-group-text justify-content-center">
      <b>Author: {{Auth::user()->name}}</b>
    </div>
  </div>
  
  </div>
  
</x-app-layout>

resources/views/articles/edit.blade.php
<x-app-layout>

  <div class="p-3">
    <div class="input-group justify-content-center">
      <h3>Редактировать: {{$article->title}}</h3>
    </div>
    <form action="{{route('articles.update',$article->id)}}" method="POST"> 
      @csrf
      @method('PATCH')
      @include('articles.form',['titleValue'=>$article->title,'textarea'=>$article->body,'submitButton'=>'Изменить'])
    </form>
    @include('errors.list')
    <div class="input-group-text justify-content-center">
      <b>Edit by: {{Auth::user()->name}}</b>
    </div>
  </div>

</x-app-layout>

resources/views/articles/form.blade.php
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1"><b>Введите название:</b></span>
      <input type='text' class="form-control" value="{{$titleValue}}" aria-describedby="basic-addon1" name='title'>
    </div>
    
    <div class="input-group-text justify-content-center">
      <span id="basic-addon1"><b> Категории статьи: </b></span>
    </div> 
    <div>
      <select class="form-control" multiple name="tag_list[]">
        @foreach ($tag as $id => $name)
          @if ($_SERVER["REQUEST_URI"]!="/articles/create")
            @if ($article->tags->pluck('id')->contains($id))
            <option class="input-group p-2 justify-content-center" value="{{$id}}" selected>
              {{$name}}
            </option>
            @else 
            <option class="input-group p-2 justify-content-center" value="{{$id}}">
              {{$name}}
            </option> 
            @endif
          @else
            <option class="input-group p-2 justify-content-center" value="{{$id}}">
              {{$name}}
            </option> 
          @endif  
        @endforeach 
      </select>
    </div>

    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1"><b>Введите описание:</b></span>
      <textarea type='text' class="form-control" name='body'>{{$textarea}}</textarea>
      <button type="submit" class="btn btn-outline-secondary"><b>{{$submitButton}}</b></button>
    </div>

<script>$(document).ready(function() {
    $('.form-control').select3();
});</script>

resources/views/articles/index.blade.php
<x-app-layout>

    <div class='p-3'>
        @unless (empty($article))
        <div class="input-group justify-content-center">
            <h3>Новые статьи:</h3>
        </div>
        
            @foreach ($article as $elem)
            <hr/>
                <article>
                    <div class="d-flex"> 
                        <div class="mr-auto p-2">
                        {{$elem->created_at->diffForHumans()}}
                        @if (!$elem->user_id==null) 
                            by 
                            @foreach ($user as $value)
                                @if ($value->id==$elem->user_id)
                                    {{$value->name}}
                                @endif
                            @endforeach
                        @endif
                            <a href="/articles/{{$elem->id}}"><h3>{{$elem->title}}</h></a>
                        </div>
                            @auth
                                @if (auth()->user()->id==$elem->user_id || auth()->user()->id==2)
                                    <div class="p-2">
                                        <a class="btn btn-warning" href="/articles/{{$elem->id}}/edit">Редактировать</a>
                                    </div>
                                    <form action="{{route('articles.destroy',$elem)}}" method="POST"> 
                                        <div class="p-2">
                                            @csrf
                                            @method('DELETE')
                                            <input class="btn btn-warning" type='submit' href="/articles/{{$elem->id}}" value="Удалить">
                                        </div>
                                    </form>
                                @endif
                            @endauth
                        </div>
                </article>
            @endforeach
        @else
        <div class="input-group justify-content-center">
            <h3>Статей нет.</h3>
        </div>
        @endunless   
        <hr/>
        <div class="input-group justify-content-center">
            <a class="input-group-text justify-content-center" href="/articles/create">
                <b>Создать статью</b>
            </a>
        </div>
    </div>
      
</x-app-layout>
    

resources/views/articles/show.blade.php
<x-app-layout>

    <div class='p-3'>
        
        <div class="input-group justify-content-center">
            
            <article>
            <div> 
                
                <div class='p-2'>
                    <h3>{{$article->title}}</h3>
                    {{$article->created_at}} 
                    by
                    @foreach ($user as $value)
                        @if ($value->id==$article->user_id)
                            {{$value->name}}
                        @endif
                    @endforeach                  
                </div>   

                <div class="d-flex">
                @auth
                    @if (auth()->user()->id==$article->user_id || auth()->user()->id==2)
                        <div class="p-2">
                            <a class="btn btn-warning" href="/articles/{{$article->id}}/edit">Редактировать</a>
                        </div>
                        <form action="{{route('articles.destroy',$article)}}" method="POST"> 
                            <div class="p-2">
                                @csrf
                                @method('DELETE')
                                <input class="btn btn-warning" type='submit' href="/articles/{{$article->id}}" value="Удалить">
                            </div>
                        </form>
                    @endif
                @endauth
                </div>

            </div>
            
            <hr/>    
            {{$article->body}}
            <hr/>
        </article>

        </div>
        @unless ($article->tags->isEmpty())
            <h5>Категории: </h5>
            <ul>
                @foreach ($article->tags as $tag)
                <li>- {{$tag->name}}</li>
                @endforeach
            </ul>
        @endunless

    </div>
    

</x-app-layout>

resources/views/articles/tags.blade.php
<x-app-layout>

    <div class='p-3'>
        @unless (empty($article))
        <div class="input-group justify-content-center">
            <h3>{{explode('/',$_SERVER['REQUEST_URI'])[2]}}</h3>
        </div>        
            @foreach ($article as $elem)
                @if ($elem->tags->pluck('name')->contains(explode('/',$_SERVER['REQUEST_URI'])[2]))
                    <hr/>
                    <article>
                        <div class="d-flex"> 
                            <div class="mr-auto p-2">
                            {{$elem->created_at->diffForHumans()}}
                            @if (!$elem->user_id==null) 
                                by 
                                @foreach ($user as $value)
                                    @if ($value->id==$elem->user_id)
                                        {{$value->name}}
                                    @endif
                                @endforeach
                            @endif
                                <a href="/articles/{{$elem->id}}"><h3>{{$elem->title}}</h></a>
                            </div>
                                @auth
                                    @if (auth()->user()->id==$elem->user_id || auth()->user()->id==2)
                                        <div class="p-2">
                                            <a class="btn btn-warning" href="/articles/{{$elem->id}}/edit">Редактировать</a>
                                        </div>
                                        <form action="{{route('articles.destroy',$elem)}}" method="POST"> 
                                            <div class="p-2">
                                                @csrf
                                                @method('DELETE')
                                                <input class="btn btn-warning" type='submit' href="/articles/{{$elem->id}}" value="Удалить">
                                            </div>
                                        </form>
                                    @endif
                                @endauth
                            </div>
                    </article>
                @endif  
            @endforeach        
        @else
        <div class="input-group justify-content-center">
            <h3>Статей нет.</h3>
        </div>
        @endunless   
        <hr/>
        <div class="input-group justify-content-center">
            <a class="input-group-text justify-content-center" href="/articles/create">
                <b>Создать статью</b>
            </a>
        </div>
    </div>
      
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
       @include ('partials.head')
    </head>

    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-300">

            <!-- Nav-menu -->
            @livewire('navigation-dropdown')
            
             <!-- Page Content -->
            <div class="py-12">
                <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                    <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">

                        @if (session('status'))
                            <div class="alert alert-success">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                {{ session('status') }}
                            </div>                  
                        @endif

                        <main>
                            {{ $slot }} 
                        </main>

                    </div>
                </div>
            </div>

            <!-- footer -->
            <div class="input-group justify-content-center">
                <i>by svel 2020</i>
            </div>

            @stack('modals')

            @livewireScripts
            
        </div>

</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        <!-- Scripts -->
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.js" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/partials/head.blade.php
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
        
        @livewireStyles

        <!-- Scripts -->
        <script src="{{ mix('js/app.js') }}" defer></script>
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>